version: "3"
services:
  db:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=postgres
     
    ports:
      - "5000:5000"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
